apiVersion: v1
kind: ServiceAccount
metadata:
  name: kthena-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kthena-controller-manager
    {{- include "kthena.labels" . | nindent 4 }}
