apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: model-validating-webhook
  labels:
    app: model-webhook
  annotations:
    cert-manager.io/inject-ca-from: matrixinfer-system/model-webhook-cert
webhooks:
- name: validate-registry-matrixinfer-ai-v1alpha1-model.matrixinfer.ai
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
  timeoutSeconds: 30
  clientConfig:
    service:
      name: model-webhook
      namespace: matrixinfer-system
      path: "/validate-registry-matrixinfer-ai-v1alpha1-model"
      port: 443
    caBundle: ""
  rules:
  - apiGroups: ["registry.matrixinfer.ai"]
    apiVersions: ["v1alpha1"]
    resources: ["models"]
    operations: ["CREATE", "UPDATE"]
    scope: "Namespaced"
