apiVersion: v1
kind: ConfigMap
metadata:
  name: model-config-map
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: model-config-map
    {{- include "matrixinfer.labels" . | nindent 4 }}
data:
  model_infer_downloader_image: "{{ .Values.modelController.downloaderImage.repository }}:{{ .Values.modelController.downloaderImage.tag }}"
  model_infer_runtime_image: "{{ .Values.modelController.runtimeImage.repository }}:{{ .Values.modelController.runtimeImage.tag }}"
