{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "matrixinfer.name" . }}-workload-validating-webhook
  labels:
    app.kubernetes.io/component: webhook
    {{- include "matrixinfer.labels" . | nindent 4 }}
  {{- if .Values.global.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "matrixinfer.name" . }}-webhook-cert
  {{- end }}
webhooks:
  - name: validate-workload-matrixinfer-ai-v1alpha1-model.matrixinfer.ai
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: {{ include "matrixinfer.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate-workload-ai-v1alpha1-modelinfer"
        port: 443
      {{- if .Values.global.certManager.enabled }}
      caBundle: ""
      {{- else }}
      caBundle: {{ .Values.webhook.caBundle | default "" | quote }}
      {{- end }}
    rules:
      - apiGroups: [ "workload.matrixinfer.ai" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelinfers" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
{{- end }}
