apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrixinfer.name" . }}-infer-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: infer-gateway
    {{- include "matrixinfer.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.inferGateway.replicas}}
  selector:
    matchLabels:
      app.kubernetes.io/component: infer-gateway
      {{- include "matrixinfer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: infer-gateway
        {{- include "matrixinfer.labels" . | nindent 8 }}
    spec:
      containers:
        - name: infer-gateway
          image: "{{ .Values.inferGateway.image.repository }}:{{ .Values.inferGateway.image.tag }}"
          imagePullPolicy: {{ .Values.inferGateway.image.pullPolicy }}
          {{- if and .Values.global.certManager.enabled .Values.inferGateway.tls.enabled }}
          args:
            - --tls-cert=/etc/tls/tls.crt
            - --tls-key=/etc/tls/tls.key
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
          resources: {{- toYaml .Values.inferGateway.resource | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
          volumeMounts:
          - name: scheduler-config
            mountPath: /etc/config/schedulerConfiguration.yaml
            subPath: schedulerConfiguration
          {{- if and .Values.global.certManager.enabled .Values.inferGateway.tls.enabled }}
          - name: tls-certs
            mountPath: "/etc/tls"
            readOnly: true
          {{- end }}
      volumes:
        - name: scheduler-config
          configMap:
            name: {{ include "matrixinfer.name" . }}-infer-gateway-config
        {{- if and .Values.global.certManager.enabled .Values.inferGateway.tls.enabled }}
        - name: tls-certs
          secret:
            secretName: {{ .Values.inferGateway.tls.secretName }}
        {{- end }}
      serviceAccountName:  {{ include "matrixinfer.name" . }}-infer-gateway
