apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrixinfer.name" . }}-infer-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: infer-gateway
    {{- include "matrixinfer.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.inferGateway.replicas}}
  selector:
    matchLabels:
      app.kubernetes.io/component: infer-gateway
      {{- include "matrixinfer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: infer-gateway
        {{- include "matrixinfer.labels" . | nindent 8 }}
    spec:
      containers:
        - name: infer-gateway
          image: "{{ .Values.inferGateway.image.repository }}:{{ .Values.inferGateway.image.tag }}"
          imagePullPolicy: {{ .Values.inferGateway.image.pullPolicy }}
          args:
            - --port={{ .Values.inferGateway.port }}
          {{- if and .Values.global.certManager.enabled .Values.inferGateway.tls.enabled }}
            - --tls-cert=/etc/tls/tls.crt
            - --tls-key=/etc/tls/tls.key
          {{- end }}
          ports:
            - containerPort: {{ .Values.inferGateway.port }}
              name: http
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST
                  optional: true
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
                  optional: true
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
                  optional: true
          resources: {{- toYaml .Values.inferGateway.resource | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.inferGateway.port }}
              {{- if and .Values.global.certManager.enabled .Values.inferGateway.tls.enabled }}
              scheme: HTTPS
              {{- end }}
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.inferGateway.port }}
              {{- if and .Values.global.certManager.enabled .Values.inferGateway.tls.enabled }}
              scheme: HTTPS
              {{- end }}
            initialDelaySeconds: 1
            periodSeconds: 5
          volumeMounts:
          - name: scheduler-config
            mountPath: /etc/config/schedulerConfiguration.yaml
            subPath: schedulerConfiguration
          {{- if and .Values.global.certManager.enabled .Values.inferGateway.tls.enabled }}
          - name: tls-certs
            mountPath: "/etc/tls"
            readOnly: true
          {{- end }}
      volumes:
        - name: scheduler-config
          configMap:
            name: {{ include "matrixinfer.name" . }}-infer-gateway-config
        {{- if and .Values.global.certManager.enabled .Values.inferGateway.tls.enabled }}
        - name: tls-certs
          secret:
            secretName: {{ .Values.inferGateway.tls.secretName }}
        {{- end }}
      serviceAccountName:  {{ include "matrixinfer.name" . }}-infer-gateway
