apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler
  labels:
    app.kubernetes.io/component: autoscaler-role-binding
    {{- include "matrixinfer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoscaler
subjects:
  - kind: ServiceAccount
    name: autoscaler
    namespace: {{ .Release.Namespace }}
