controllerManager:
  webhook:
    enabled: true
  # replicas is the number of instances to run.
  replicas: 1
  image:
    repository: ghcr.io/volcano-sh/kthena-controller-manager
    # node: edit by CI. No need to modify manually
    tag: latest
    pullPolicy: IfNotPresent
    # enable-webhook to false to disable webhook, default is true
    args: [ "--v=2" ]
  resource:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  # downloaderImage is the container image used for downloading models.
  downloaderImage:
    repository: ghcr.io/volcano-sh/downloader
    # node: edit by CI. No need to modify manually
    tag: latest
  # runtimeImage is the container image used for running models.
  runtimeImage:
    repository: ghcr.io/volcano-sh/runtime
    # node: edit by CI. No need to modify manually
    tag: latest
  downloader:
    # accessKey is the access key for the downloader.
    accessKey: ""
    # secretKey is the secret key for the downloader.
    secretKey: ""

global:
  certManager:
    enabled: true
  webhook:
  # caBundle is the base64-encoded CA bundle for webhook server certificates.
  # This is required when cert-manager is disabled (global.certManager.enabled=false).
  # You can generate it with: cat /path/to/your/ca.crt | base64 | tr -d '\n'
  # caBundle: ""
