apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: model-controller
  labels:
    app.kubernetes.io/component: model-controller-role-binding
    {{- include "matrixinfer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: model-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "matrixinfer.fullname" . }}-model-controller
    namespace: {{ .Release.Namespace }}
