apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrixinfer.fullname" . }}-model-controller-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: model-controller
    {{- include "matrixinfer.labels" . | nindent 4 }}
data:
  model_infer_downloader_image: "{{ .Values.modelController.downloaderImage.repository }}:{{ .Values.modelController.downloaderImage.tag }}"
  model_infer_runtime_image: "{{ .Values.modelController.runtimeImage.repository }}:{{ .Values.modelController.runtimeImage.tag }}"
