apiVersion: v1
kind: Secret
metadata:
  name: downloader-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: downloader-secrets
    {{- include "matrixinfer.labels" . | nindent 4 }}
data:
  ACCESS_KEY: {{ .Values.modelController.downloader.accessKey | b64enc | quote }}
  ENDPOINT: {{ .Values.modelController.downloader.endpoint | b64enc | quote }}
  SECRET_KEY: {{ .Values.modelController.downloader.secretKey | b64enc | quote }}
type: Opaque
  