apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - modelboosters
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - modelboosters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - autoscalingpolicies
      - autoscalingpolicybindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - autoscalingpolicies/status
      - autoscalingpolicybindings/status
    verbs:
      - get
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - autoscalingpolicies/finalizers
      - autoscalingpolicybindings/finalizers
      - modelboosters/finalizers
    verbs:
      - update
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - modelservings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - modelservings/status
    verbs:
      - get
  - apiGroups:
      - networking.serving.volcano.sh
    resources:
      - modelroutes
      - modelservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.serving.volcano.sh
    resources:
      - modelroutes/status
      - modelservers/status
    verbs:
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch