---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: autoscalingpolicies.registry.matrixinfer.ai
spec:
  group: registry.matrixinfer.ai
  names:
    kind: AutoscalingPolicy
    listKind: AutoscalingPolicyList
    plural: autoscalingpolicies
    singular: autoscalingpolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AutoscalingPolicy is the Schema for the autoscalingpolicies API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: AutoscalingPolicySpec defines the desired state of AutoscalingPolicy.
            properties:
              behavior:
                description: Behavior defines the scaling behavior for both scale
                  up and scale down.
                properties:
                  scaleDown:
                    description: ScaleDown defines the policy for scaling down (decreasing
                      replicas).
                    properties:
                      instances:
                        default: 1
                        description: Instances is the maximum number of instances
                          to scale.
                        format: int32
                        minimum: 0
                        type: integer
                      percent:
                        default: "100"
                        description: Percent is the maximum percentage of instances
                          to scaling.
                        format: int32
                        maximum: 1000
                        minimum: 0
                        type: integer
                      period:
                        default: 15s
                        description: Period is the duration over which scaling is
                          evaluated.
                        type: string
                      selectPolicy:
                        description: SelectPolicy determines the selection strategy
                          for scaling up (e.g., Or, And).
                        enum:
                        - Or
                        - And
                        type: string
                      stabilizationWindow:
                        description: StabilizationWindow is the time window to stabilize
                          scaling up actions.
                        type: string
                    type: object
                  scaleUp:
                    description: ScaleUp defines the policy for scaling up (increasing
                      replicas).
                    properties:
                      panicPolicy:
                        description: AutoscalingPolicyPanicPolicy defines the policy
                          for panic scaling up.
                        properties:
                          panicModeHold:
                            description: PanicModeHold is the duration to hold in
                              panic mode before returning to normal.
                            type: string
                          panicThresholdPercent:
                            description: PanicThresholdPercent is the threshold percent
                              to enter panic mode.
                            format: int32
                            maximum: 1000
                            minimum: 110
                            type: integer
                          percent:
                            description: Percent is the maximum percentage of instances
                              to scale up.
                            format: int32
                            maximum: 1000
                            minimum: 0
                            type: integer
                          period:
                            description: Period is the duration over which scaling
                              down is evaluated.
                            type: string
                        required:
                        - period
                        type: object
                      stablePolicy:
                        description: AutoscalingPolicyStablePolicy defines the policy
                          for stable scaling up or scaling down.
                        properties:
                          instances:
                            default: 1
                            description: Instances is the maximum number of instances
                              to scale.
                            format: int32
                            minimum: 0
                            type: integer
                          percent:
                            default: "100"
                            description: Percent is the maximum percentage of instances
                              to scaling.
                            format: int32
                            maximum: 1000
                            minimum: 0
                            type: integer
                          period:
                            default: 15s
                            description: Period is the duration over which scaling
                              is evaluated.
                            type: string
                          selectPolicy:
                            description: SelectPolicy determines the selection strategy
                              for scaling up (e.g., Or, And).
                            enum:
                            - Or
                            - And
                            type: string
                          stabilizationWindow:
                            description: StabilizationWindow is the time window to
                              stabilize scaling up actions.
                            type: string
                        type: object
                    type: object
                type: object
              metrics:
                description: Metrics is the list of metrics used to evaluate scaling
                  decisions.
                items:
                  description: AutoscalingPolicyMetric defines a metric and its target
                    value for scaling.
                  properties:
                    metricName:
                      description: MetricName is the name of the metric to monitor.
                      type: string
                    targetValue:
                      anyOf:
                      - type: integer
                      - type: string
                      description: TargetValue is the target value for the metric
                        to trigger scaling.
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                  required:
                  - metricName
                  - targetValue
                  type: object
                minItems: 1
                type: array
              tolerancePercent:
                default: 10
                description: TolerancePercent is the percentage of deviation tolerated
                  before scaling actions are triggered.
                format: int32
                maximum: 100
                minimum: 0
                type: integer
            required:
            - metrics
            type: object
          status:
            description: AutoscalingPolicyStatus defines the observed state of AutoscalingPolicy.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
