apiVersion: v1
kind: Service
metadata:
  name: kthena-router
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kthena-router
    {{- include "kthena.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: kthena-router
    {{- include "kthena.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.kthenaRouter.port }}
      name: http
  type: LoadBalancer
---
{{- if and .Values.kthenaRouter.enabled .Values.kthenaRouter.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kthena.name" . }}-kthena-router-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kthena-router
    {{- include "kthena.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: kthena-router
    {{- include "kthena.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.kthenaRouter.webhook.servicePort }}
      targetPort: {{ .Values.kthenaRouter.webhook.port }}
      name: webhook
  type: ClusterIP
{{- end }}
