{{- if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrixinfer.fullname" . }}-registry-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: registry-webhook
    {{- include "matrixinfer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: registry-webhook
      {{- include "matrixinfer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: registry-webhook
        {{- include "matrixinfer.labels" . | nindent 8 }}
    spec:
      containers:
        - name: webhook
          image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          args: {{ .Values.webhook.image.args }}
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          resources: {{- toYaml .Values.webhook.resource | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: webhook-certs
          secret:
            secretName: registry-webhook-certs
      serviceAccountName: registry-webhook
{{- end }}
