{{- if .Values.registryWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrixinfer.fullname" . }}-registry-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: registry-webhook
    {{- include "matrixinfer.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 8443
      name: https
  selector:
    app.kubernetes.io/component: registry-webhook
    {{- include "matrixinfer.selectorLabels" . | nindent 4 }}
{{- end }}
