inferGateway:
  # replicas is the number of infer-gateway instances to run.
  replicas: 1
  enabled: true
  tls:
    enabled: false
    # The DNS name to use for the certificate.
    dnsName: ""
    # The name of the secret to store the certificate and key.
    secretName: "infer-gateway-tls"
  image:
    # repository is the container image repository for the infer-gateway.
    repository: ghcr.io/matrixinfer-ai/infer-gateway
    # tag is the container image tag for the infer-gateway.
    tag: latest
    # pullPolicy is the image pull policy for the infer-gateway.
    pullPolicy: IfNotPresent
  # resource defines the resource limits and requests for the infer-gateway.
  resource:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

webhook:
  enabled: true
  # replicas is the number of gateway-webhook instances to run.
  replicas: 1
  image:
    # repository is the container image repository for the gateway-webhook.
    repository: ghcr.io/matrixinfer-ai/gateway-webhook
    # tag is the container image tag for the gateway-webhook.
    tag: latest
    # pullPolicy is the image pull policy for the gateway-webhook.
    pullPolicy: IfNotPresent
    # args are the command line arguments for the gateway-webhook.
    args: [ "--port=8443", "--webhook-timeout=30" ]
  # resource defines the resource limits and requests for the gateway-webhook.
  resource:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi