apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infer-controller
  labels:
    app.kubernetes.io/instance: infer-controller-role-binding
    {{- include "matrixinfer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infer-controller
subjects:
  - kind: ServiceAccount
    name: infer-controller
    namespace: {{ .Release.Namespace }}
