{{- if .Values.registryWebhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: registry-webhook
    {{- include "matrixinfer.labels" . | nindent 4 }}
{{- end }}
